# Base image
FROM python:3.12-slim-bookworm

ARG DEBIAN_PACKAGES="build-essential curl"

# Prevent apt from showing prompts
ENV DEBIAN_FRONTEND=noninteractive

# Python wants UTF-8 locale
ENV LANG=C.UTF-8

# Tell Python to disable buffering so we don't lose any logs.
ENV PYTHONUNBUFFERED=1

# Tell uv to copy packages from the wheel into the site-packages
ENV UV_LINK_MODE=copy
ENV UV_PROJECT_ENVIRONMENT=/app/.venv
##ENV UV_PROJECT_ENVIRONMENT=/.venv


# ENV GOOGLE_APPLICATION_CREDENTIALS=../secrets/llm-service-account.json
ENV GCP_PROJECT="mineral-style-471117-k1"


# Ensure we have an up to date baseline, install dependencies and
# create a user so we don't run the app as root
RUN set -ex; \
    for i in $(seq 1 8); do mkdir -p "/usr/share/man/man${i}"; done && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends $DEBIAN_PACKAGES && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir --upgrade pip && \
    pip install uv && \
    useradd -ms /bin/bash app -d /home/app -u 1000 && \
    mkdir -p /app && \
    chown app:app /app
    #mkdir -p /.venv && \
    #chown app:app /.venv

# Switch to the new user
USER app
# Workdir inside /app
WORKDIR /app

# Copy the source code
COPY --chown=app:app . ./
# COPY --chown=app:app pyproject.toml uv.lock* ./

RUN uv sync
# Install dependencies in a separate layer for better caching
# RUN uv sync --frozen
# Copy the rest of the source code
#COPY --chown=app:app . ./

# Entry point
ENTRYPOINT ["/bin/bash"]
# Get into the uv virtual environment shell
CMD ["-c", "source /app/.venv/bin/activate && exec bash"]
#ENTRYPOINT ["/bin/bash","docker-entrypoint.sh"]
#CMD ["/bin/bash"]

# This is done for the tutorial only    ENV GOOGLE_APPLICATION_CREDENTIALS=secrets/mega-pipeline.json



